# Generated by Django 5.0.6 on 2024-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdb',
            name='image_url',
            field=models.ImageField(null=True, upload_to='MainApp\\static\\img'),
        ),
    ]
