# Generated by Django 5.0.6 on 2024-07-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0004_remove_itemdb_image_url_itemdb_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdb',
            old_name='image',
            new_name='image_url',
        ),
    ]
